[package]
authors = ["The Nushell Project Developers"]
description = "Nushell table printing"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-table"
edition = "2024"
license = "MIT"
name = "nu-table"
version = "0.108.1-nightly.6"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
nu-protocol = { path = "../nu-protocol", version = "0.108.1-nightly.6", default-features = false }
nu-utils = { path = "../nu-utils", version = "0.108.1-nightly.6", default-features = false }
nu-engine = { path = "../nu-engine", version = "0.108.1-nightly.6", default-features = false }
nu-color-config = { path = "../nu-color-config", version = "0.108.1-nightly.6" }
nu-ansi-term = { workspace = true }
fancy-regex = { workspace = true }
tabled = { workspace = true, features = ["ansi"], default-features = false }

[dev-dependencies]
# nu-test-support = { path="../nu-test-support", version = "0.108.1-nightly.6"  }
