#
# REF:
#   1. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixinclude
#
name: Create Windows Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Nu

    strategy:
      fail-fast: false
      matrix:
        target:
        - x86_64-pc-windows-msvc
        - aarch64-pc-windows-msvc
        extra: ['bin']

        include:
        - target: x86_64-pc-windows-msvc
          extra: 'bin'
          os: windows-latest
        - target: aarch64-pc-windows-msvc
          extra: 'bin'
          os: windows-11-arm

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Wix Toolset 6 for Windows
      shell: pwsh
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: |
        dotnet tool install --global wix --version 6.0.0
        dotnet workload install wix
        $wixPath = "$env:USERPROFILE\.dotnet\tools"
        echo "$wixPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "$wixPath;$env:PATH"
        wix --version

    - name: Update Rust Toolchain Target
      run: |
        echo "targets = ['${{matrix.target}}']" >> rust-toolchain.toml

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      # WARN: Keep the rustflags to prevent from the winget submission error: `CAQuietExec: Error 0xc0000135`
      with:
        cache: false
        rustflags: ''

    - name: Setup Nushell
      uses: hustcer/setup-nu@v3
      if: ${{ matrix.os != 'windows-11-arm' }}
      with:
        version: 0.103.0

    - name: Release Nu Binary
      id: nu
      if: ${{ matrix.os != 'windows-11-arm' }}
      run: nu .github/workflows/release-pkg.nu
      env:
        OS: ${{ matrix.os }}
        REF: ${{ github.ref }}
        TARGET: ${{ matrix.target }}
        _EXTRA_: ${{ matrix.extra }}

    - name: Build Nu for Windows ARM64
      id: nu0
      shell: pwsh
      if: ${{ matrix.os == 'windows-11-arm' }}
      run: |
        $env:OS = 'windows'
        $env:REF = '${{ github.ref }}'
        $env:TARGET = '${{ matrix.target }}'
        $env:_EXTRA_ = '${{ matrix.extra }}'
        cargo build --release --all --target aarch64-pc-windows-msvc
        cp ./target/${{ matrix.target }}/release/nu.exe .
        ./nu.exe -c 'version'
        ./nu.exe ${{github.workspace}}/.github/workflows/release-pkg.nu

    # REF: https://github.com/marketplace/actions/gh-release
    - name: Publish Archive
      uses: softprops/action-gh-release@v2.2.2
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: |
          ${{ steps.nu.outputs.msi }}
          ${{ steps.nu0.outputs.msi }}
          ${{ steps.nu.outputs.archive }}
          ${{ steps.nu0.outputs.archive }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sha256sum:
    needs: release
    name: Create Sha256sum
    runs-on: ubuntu-latest
    steps:
    - name: Download Release Archives
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release download ${{ github.ref_name }}
        --repo ${{ github.repository }}
        --pattern '*'
        --dir release
    - name: Create Checksums
      run: cd release && shasum -a 256 * > ../SHA256SUMS
    - name: Publish Checksums
      uses: softprops/action-gh-release@v2.2.2
      with:
        files: SHA256SUMS
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
